### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by pocesar** [telehash/telehash-js#25]
Any ETA release for v3 of Telehash-js?

**Comment by quartzjer** [comment]
I would track issue [#111](https://github.com/telehash/telehash.org/issues/111) for overall v3-stable updates, I've been focusing on getting telehash-c on par with telehash-js and there should be some stability/docs/examples prep work happening here yet this month to prep for a full js release (need a lot more browser testing yet).

**Comment by pocesar** [comment]
alright, thanks for the feedback :+1:

**Comment by anhldbk** [comment]
@quartzjer This issue should be closed, right?
