### ISSUE TITLE
Reference to a global telehash that doesn't exist

### ISSUE THREAD

**Issue by latentflip** [telehash/telehash-js#44]
There's a reference to `telehash` here that's undefined, it's blowing up if I try and run bin/link.js

https://github.com/telehash/telehash-js/blob/master/lib/mesh.class.js#L103

**Comment by latentflip** [comment]
Perhaps this is supposed to just be `this.extensions`?

**Comment by rynomad** [comment]
Hey there. I just patched it in the 0.3.30 branch, (somethings going wrong in travis for iojs so I don't want to pull it into master yet). sorry about that... I think there was some inconsistency when I made the last run of merges to the master branch. I've got to run out right now but 0.3.30 (as well as what's published on npm) should have the problem solved till I can sit down and smooth everything

**Comment by rynomad** [comment]
getting over the fear of closing issues. This has been fixed for a bit. definitely good to go with 0.4.0
