### ISSUE TITLE
NAT Traversal

### ISSUE THREAD

**Issue by ghost** [telehash/telehash-js#60]
Hi,

I found your library while searching Google about NAT Traversal.
I need a Nodejs Library for NAT Traversal.

I could not find any documentation about NAT Traversal for Telehash.
Can I use your library for this purpose?
Thanks in advance.

**Comment by stpeter** [comment]
NAT traversal is a complex topic and it's not really the core focus of telehash. Depending on what you need it for (e.g., WebRTC), I'd suggest looking around for JavaScript modules that implement the STUN and TURN protocols.
